export const CourseDataDetails = [
    {
        id:"1",
        title:"Data Science",
        image:"https://www.tqmi.com/wp-content/uploads/2022/02/Data-Science-4.webp",
        courseDetails:"Data science combines math and statistics, specialized programming, advanced analytics, artificial intelligence (AI), and machine learning",
        topic1:"Programming in C",
        topic2:"Machine Learning",
        topic3:"Data Visualizations",
        topic4:"Database Management Systems",
        topic5:"Data Structures and Program Design in C",
        price:"15,000",        
    },
    {
        id:"2",
        title:"Full Stack Developer",
        image:"https://gisgeography.com/wp-content/uploads/2022/03/Full-Stack-Developer-Certification.png",
        courseDetails:"",
        topic1:"HTML5, CSS3, Bootstrap5",
        topic2:"JavaScript",
        topic3:"NodeJS",
        topic4:"MomgoDB",
        topic5:"Java",
        price:"21,700",        
    },
    {
        id:"3",
        title:"Java Developer",
        image:"https://miro.medium.com/v2/resize:fit:600/1*fOdb_ET1sOd4uZStK4E8HA.jpeg",
        courseDetails:"Responsible for developing applications and software using the Java programming language",
        topic1:"HTML, CSS, and JavaScript",
        topic2:"Data Types and Variables",
        topic3:"JAVA IO Streams",
        topic4:"Features and Architecture",
        topic5:"Core Java",
        price:"25,599",        
    },
    {
        id:"4",
        title:"ReactJS developer",
        image:"https://assets-global.website-files.com/6265268a49337ba3053228fa/6347218bd639fe67694eeafa_Hero%20template%209.png",
        courseDetails:"A React. js developer is a professional software developer or web developer who uses React to create websites and apps.",
        topic1:"HTML5, CSS3",
        topic2:"Bootstrap5",
        topic3:"JavaScript",
        topic4:"ReactJS",
        topic5:"NodeJS",
        price:"31,999", 
      
    },
    {
        id:"5",
        title:"Graphic Design",
        image:"https://res.cloudinary.com/hamstech/images/f_auto,q_auto/v1637134439/Hamstech%20App/Title-Image-4_80465274aebb5/Title-Image-4_80465274aebb5.jpg?_i=AA",
        courseDetails:"Graphic design is a craft where professionals create visual content to communicate messages.",
        topic1:"Photoshop",
        topic2:"UI graphics",
        topic3:"Figma",
        topic4:"Adobe XD",
        topic5:"3D Modeling and Prototyping",
        price:"15,500",         
    },
    {
        id:"6",
        title:"Python Developer",
        image:"https://cache.careers360.mobi/media/presets/860X430/article_images/2021/9/6/18-beginner-courses-on-Django-to-become-a-full-stack-Python-developer.webp",
        courseDetails:"Python Developers often work server side, either writing logic or developing the platform.",
        topic1:"Python",
        topic2:"Django",
        topic3:"Object Relational Mapper",
        topic4:"Flask",
        topic5:"Core Python",
        price:"17,100",        
    },
    {
        id:"7",
        title:"React Native",
        image:"https://www.hammer.net/wp-content/uploads/2023/02/react-native_large.jpg",
        courseDetails:"React Native is an open-source JavaScript framework, designed for building apps on multiple platforms like iOS, Android, and also web applications",
        topic1:"Native Core Components",
        topic2:"CSS",
        topic3:"JavaScript",
        topic4:"TypeScript",
        topic5:"NodeJS",
        price:"19,999",        
    },
    {
        id:"8",
        title:"Ethical Hacking",
        image:"https://d30i16bbj53pdg.cloudfront.net/wp-content/uploads/2021/02/ethical-hacking-web.jpeg",
        courseDetails:"Ethical hacking involves an authorized attempt to gain unauthorized access to a computer system, application, or data.",
        topic1:"Testing",
        topic2:"Exploitation",
        topic3:"System Hacking",
        topic4:"Linux OS",
        topic5:"Hacking Web Applications",
        price:"10,799",        
    },
    {
        id:"9",
        title:"Coding Fundamentals",
        image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9m_kWqQaimik2VkoKJbOEKhNWx9xNeMvDJTrGWDVTXHxiOnjM9sy3q62eFjnu2QLTV_Q&usqp=CAU",
        courseDetails:"variable declaration, basic control structures, data structures, object-oriented programming, troubleshooting and debugging, and various programming tools.",
        topic1:"JavaScript",
        topic2:"Algorithm",
        topic3:"Data Stucture",
        topic4:"C and C++",
        topic5:"Python and Java",
        price:"13,599",        
    },
    {
        id:"10",
        title:"Job Ready",
        image:"https://www.myamcat.com/blog/wp-content/uploads/2016/01/bigstock-Job-Search-Qualification-Resum-87321434-740x431.jpg",
        courseDetails:"Learn about the jobs you are applying for, understand your skills, and make sure your resume has the information employers are looking for.",
        topic1:"Communication",
        topic2:"Interview Skills",
        topic3:"Resume Buildings",
        topic4:"Workplace Etiquette",
        topic5:"Apptitude",
        price:"13,799",        
    },
]